config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'

  resources :cocktails, except: :destroy do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates_uniqueness_of :ingredient_id, scope: :cocktail_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(params_cocktails)
    @cocktail.save

    redirect_to cocktail_path(@cocktail)
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(params_cocktails)

    redirect_to cocktail_path(@cocktail)
  end

  private

  def params_cocktails
    params.require(:cocktail).permit(:name, :photo, :description)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(params_dose)
    @dose.cocktail = @cocktail
    @dose.save
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def params_dose
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>

<% end %>

app/views/cocktails/edit.html.erb
<%= render 'form', cocktail: @cocktail %>

app/views/cocktails/index.html.erb
<%= render './shared/banner', banner_url: "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png", title: "Become a cocktail master!", description: "Impress your friends! Find the best cocktail recipes and Do it!" %>
<%= render './shared/search_bar' %>


<div class="cards-container">
  <div class="row">
      <% @cocktails.each do |cocktail| %>
        <div class="card-container col-xm-12 col-md-6 col-lg-4 ">
          <% if cocktail.photo.attached? %>
            <%= link_to cocktail_path(cocktail), class:"card-category", style:"background-image:linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(#{cl_image_path cocktail.photo.key }" do %>
              <div><%= cocktail.name %></div>
            <% end %>
          <% else %>
            <%= link_to cocktail_path(cocktail), class:"card-category", style:"background-image:linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(#{cl_image_path "vaffbtjbtvyqkmybgq8a"}" do %>
              <div><%= cocktail.name %></div>
            <% end %>
          <% end %>
        </div>
      <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>Create a new cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to "Back to Coktails list", cocktails_path %>

app/views/cocktails/show.html.erb
<% if @cocktail.photo.attached? %>
<div class="banner-cocktail"  style="background-image: linear-gradient(110deg, rgba(0,0,0,0) 40%,rgba(0,0,0,0.8) 100%), url(<%= cl_image_path(@cocktail.photo.key) %>);">
<% else %>
<div class="banner-cocktail"  style="background-color: linear-gradient(110deg, rgba(0,0,0,0) 40%,rgba(0,0,0,0.8) 100%);">
<% end %>
  <div class="container">
    <div class="offset-md-6 ">
      <div class="banner-header d-flex flex-column align-items-center">
        <h1><%= @cocktail.name %></h1>
        <p><%= @cocktail.description %></p>
      </div>

      <div class="container-ingredients">
        <h2>Liste des ingrédients :</h2>
        <ul class="list-ingredients">
          <% @cocktail.doses.each do |dose| %>
          <li>
            <%= link_to dose_path(dose), method: :delete do %>
            <i class="far fa-times-circle"></i>
            <% end %><%= dose.description %> de <%= dose.ingredient.name %>
            </li>
          <% end %>
        </ul>
      </div>


        <div class="btn btn-ghost edit-button add-ingredient">
          <i class="far fa-edit"></i> Add new ingredient
        </div>

      <%= link_to edit_cocktail_path(@cocktail) do %>
        <div class="btn btn-ghost edit-button">
          <i class="far fa-edit"></i> Edit cocktail
        </div>
      <% end %>

      <%= render partial: "doses/new", cocktail: @cocktail, dose: @dose %>

    </div>
  </div>

  <%= link_to cocktails_path do %>
    <div class="">
      <i class="fas fa-undo-alt"></i>Back to cocktails list
    </div>
  <% end %>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient, collection: Ingredient.order(:name), prompt: "Choose a ingredient" %>

  <%= f.submit %>
<% end %>

app/views/doses/_new.html.erb
<div id="new-dose" class="unvisible">
  <h1>Add a new dose</h1>

  <%= render 'doses/form', dose: @dose %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">



    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>     <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/shared/_banner-cocktail.html.erb
<!-- <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);"> -->
<div class="banner-cocktail"  style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= banner_url %>);">
  <div class="offset-md-6 container">
    <div class="d-flex flex-column align-items-center">
      <h1><%= title %></h1>
      <p> <%= description %></p>


    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<!-- <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);"> -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= banner_url %>);">
  <div class="container">
    <h1><%= title %></h1>
    <p> <%= description %></p>
    <a class="btn btn-primary" href="#">Find a cocktail!</a>
  </div>
</div>

app/views/shared/_search_bar.html.erb
<div class="search_bar">

  <%= link_to "Add a new cocktail", new_cocktail_path, class: "btn btn-flat" %>

</div>